import { MantineProvider } from "@mantine/core";
import "@mantine/core/styles.css";
import "../../styles/main.scss";
import { theme } from "../../lib/mantineTheme";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <MantineProvider theme={theme}>
          <main>{children}</main>
        </MantineProvider>
      </body>
    </html>
  );
}
