export const verificationStatus = {
  SUCCESS: "SUCCESS",
  ALREADY_VERIFIED: "ALREADY_VERIFIED",
  UNAUTHENTICATED: "UNAUTHENTICATED",
  UNAUTHORIZED: "UNAUTHORIZED",
  EXPIRED: "EXPIRED",
  INVALID: "INVALID",
  FORBIDDEN: "FORBIDDEN",
  USED: "USED",
  ERROR: "ERROR",
  TOO_SOON: "TOO_SOON",
};
